siis/controllers/RapportController.php
<?php

namespace app\controllers;

use app\models\Communes;
use app\models\Options;
use kartik\mpdf\Pdf;
use Yii;

class RapportController extends \yii\web\Controller
{
	public $layout = 'main_dashboard2';
	public $comm;
	public $total;
	public $total_enfantgarcon05;
	public $total_enfantfille05;
	public $total_enfantgarcon518;
	public $total_enfantfille518;
	public $total_localite;
	public $total_f;
	public $total_m;
	
	public function actionDimensions()
	{
		$model = new Options();
		
		if ($model->load(Yii::$app->request->post()))
		{
			/* print_r($model->question);
			print_r($model->commune);
			print_r($model->section_communale);
			print_r($model->localite); */
			
			$options_array = array();
			$o = 0;
			foreach ($model->question as $c){
				$obj = Options::find()->where(['id' => $c])->one();
				$options_array[$o] = $obj;
				//print_r($options_array[$o]);
				$o += 1;
			}
			
			$content = $this->renderPartial('pdfstats', [
				'data' => $options_array,
				'commune' => $model->commune,
				'section_communale' => $model->section_communale,
				'localite' => $model->localite
			]);
			
			$nom = 'Statistiques Enquetes FAES - Avril 2015';
	
			$pdf = new Pdf();
			$pdf->mode = Pdf::MODE_UTF8;
			$pdf->cssFile = '@vendor/kartik-v/yii2-mpdf/assets/kv-mpdf-bootstrap.min.css';
			$pdf->defaultFontSize = 10;
			$pdf->defaultFont = 'helvetica';
			$pdf->format = array(216,285);
			$pdf->orientation = Pdf::ORIENT_LANDSCAPE;
			$pdf->destination = Pdf::DEST_BROWSER;
			$pdf->content = $content;
			$pdf->options = [
				'title' => $nom,
				'autoScriptToLang' => true,
				'ignore_invalid_utf8' => true,
				'tabSpaces' => 4
			];
			$pdf->methods = [
				'SetHeader'=>['Donnee Enquetes Avril 2015'],
				'SetFooter'=>['{PAGENO}'],
			];
		
			return $pdf->render();
			
		}else{
			return $this->render('dimensions',[
				'model' => $model
			]);
		}
	}
	
	public function actionPdfcarnet450()
	{
		
	}
	
	public function actionListquestion($dimension)
	{
		$communes = Options::find()->select('question')->distinct()->where(['dimension' => $dimension])
		->orderBy('question')->all();
	
		$count = Options::find()->select('question')->distinct()->where(['dimension' => $dimension])
		->orderBy('question')->count();
	
		if($count > 0)
		{
			echo "<option value>--Choisir une question --</option>";
			foreach ($communes as $commun){
				echo "<option value='".$commun->id."'>".$commun->question."</option>";
			}
		}
		else
		{
			echo "<option value>--Choisir une question --</option>";
			return "<option></option>";
		}
	}
	
	public function actionSanitairethomassique()
	{
		$this->comm = $this->getCommunes();
		$this->total = $this->getTotal1('Thomassique');
		$edh = $this->getLumiere('Thomassique');
		$cuisines = $this->getCuisines('Thomassique');
		$maisons = $this->getMaisons('Thomassique');
		$toits = $this->getToits('Thomassique');
		$kalite = $this->getTotalkalitekay('Thomassique');
		$latrine1 = $this->getTotallatrine('Thomassique', 1);
		$latrine2 = $this->getTotallatrine('Thomassique', 2);
		$latrine3 = $this->getTotallatrine('Thomassique', 3);
		$latrine7 = $this->getTotallatrine('Thomassique', 7);
		
		return $this->render('sanitairethomassique',[
			'comm'=>$this->comm,
			'total'=>$this->total,
			'edh'=>$edh,
			'cuisines' => $cuisines,
			'maisons' => $maisons,
			'toits' => $toits,
			'kalite' => $kalite,
			'latrine1' => $latrine1,
				'latrine2' => $latrine2,
				'latrine3' => $latrine3,
				'latrine7' => $latrine7,
		]);
	}
	
	public function actionSanitaireansespitre()
	{
		$this->comm = $this->getCommunes();
		$this->total = $this->getTotal1('anse_pitres');
		$edh = $this->getLumiere('anse_pitres');
		$cuisines = $this->getCuisines('anse_pitres');
		$maisons = $this->getMaisons('anse_pitres');
		$toits = $this->getToits('anse_pitres');
		$kalite = $this->getTotalkalitekay('anse_pitres');
		$latrine1 = $this->getTotallatrine('anse_pitres', 1);
		$latrine2 = $this->getTotallatrine('anse_pitres', 2);
		$latrine3 = $this->getTotallatrine('anse_pitres', 3);
		$latrine7 = $this->getTotallatrine('anse_pitres', 7);
	
		return $this->render('sanitaireansespitre',[
				'comm'=>$this->comm,
				'total'=>$this->total,
				'edh'=>$edh,
				'cuisines' => $cuisines,
				'maisons' => $maisons,
				'toits' => $toits,
				'kalite' => $kalite,
				'latrine1' => $latrine1,
				'latrine2' => $latrine2,
				'latrine3' => $latrine3,
				'latrine7' => $latrine7,
				]);
	}
	
	public function actionSanitairethiotte()
	{
		$this->comm = $this->getCommunes();
		$this->total = $this->getTotal1('thiotte');
		$edh = $this->getLumiere('thiotte');
		$cuisines = $this->getCuisines('thiotte');
		$maisons = $this->getMaisons('thiotte');
		$toits = $this->getToits('thiotte');
		$kalite = $this->getTotalkalitekay('thiotte');
		$latrine1 = $this->getTotallatrine('thiotte', 1);
		$latrine2 = $this->getTotallatrine('thiotte', 2);
		$latrine3 = $this->getTotallatrine('thiotte', 3);
		$latrine7 = $this->getTotallatrine('thiotte', 7);
	
		return $this->render('sanitairethiotte',[
				'comm'=>$this->comm,
				'total'=>$this->total,
				'edh'=>$edh,
				'cuisines' => $cuisines,
				'maisons' => $maisons,
				'toits' => $toits,
				'kalite' => $kalite,
				'latrine1' => $latrine1,
				'latrine2' => $latrine2,
				'latrine3' => $latrine3,
				'latrine7' => $latrine7,
				]);
	}
	
	public function actionSanitairegosier()
	{
		$this->comm = $this->getCommunes();
		$this->total = $this->getTotal1('grand_gosier');
		$edh = $this->getLumiere('grand_gosier');
		$cuisines = $this->getCuisines('grand_gosier');
		$maisons = $this->getMaisons('grand_gosier');
		$toits = $this->getToits('grand_gosier');
		$kalite = $this->getTotalkalitekay('grand_gosier');
		$latrine1 = $this->getTotallatrine('grand_gosier', 1);
		$latrine2 = $this->getTotallatrine('grand_gosier', 2);
		$latrine3 = $this->getTotallatrine('grand_gosier', 3);
		$latrine7 = $this->getTotallatrine('grand_gosier', 7);
	
		return $this->render('sanitairegosier',[
				'comm'=>$this->comm,
				'total'=>$this->total,
				'edh'=>$edh,
				'cuisines' => $cuisines,
				'maisons' => $maisons,
				'toits' => $toits,
				'kalite' => $kalite,
				'latrine1' => $latrine1,
				'latrine2' => $latrine2,
				'latrine3' => $latrine3,
				'latrine7' => $latrine7,
				]);
	}
	
	public function actionSanitaireboucan()
	{
		$this->comm = $this->getCommunes();
		$this->total = $this->getTotal1('boucan_carre');
		$edh = $this->getLumiere('boucan_carre');
		$cuisines = $this->getCuisines('boucan_carre');
		$maisons = $this->getMaisons('boucan_carre');
		$toits = $this->getToits('boucan_carre');
		$kalite = $this->getTotalkalitekay('boucan_carre');
		$latrine1 = $this->getTotallatrine('boucan_carre', 1);
		$latrine2 = $this->getTotallatrine('boucan_carre', 2);
		$latrine3 = $this->getTotallatrine('boucan_carre', 3);
		$latrine7 = $this->getTotallatrine('boucan_carre', 7);
	
		return $this->render('sanitairegosier',[
				'comm'=>$this->comm,
				'total'=>$this->total,
				'edh'=>$edh,
				'cuisines' => $cuisines,
				'maisons' => $maisons,
				'toits' => $toits,
				'kalite' => $kalite,
				'latrine1' => $latrine1,
				'latrine2' => $latrine2,
				'latrine3' => $latrine3,
				'latrine7' => $latrine7,
				]);
	}
	
	public function actionSanitairesautdeau()
	{
		$this->comm = $this->getCommunes();
		$this->total = $this->getTotal1("Saut d\'eau");
		$edh = $this->getLumiere("Saut d\'eau");
		$cuisines = $this->getCuisines("Saut d\'eau");
		$maisons = $this->getMaisons("Saut d\'eau");
		$toits = $this->getToits("Saut d\'eau");
		$kalite = $this->getTotalkalitekay("Saut d\'eau");
		$latrine1 = $this->getTotallatrine("Saut d\'eau", 1);
		$latrine2 = $this->getTotallatrine("Saut d\'eau", 2);
		$latrine3 = $this->getTotallatrine("Saut d\'eau", 3);
		$latrine7 = $this->getTotallatrine("Saut d\'eau", 7);
	
		return $this->render('sanitairesautdeau',[
				'comm'=>$this->comm,
				'total'=>$this->total,
				'edh'=>$edh,
				'cuisines' => $cuisines,
				'maisons' => $maisons,
				'toits' => $toits,
				'kalite' => $kalite,
				'latrine1' => $latrine1,
				'latrine2' => $latrine2,
				'latrine3' => $latrine3,
				'latrine7' => $latrine7,
				]);
	}
	
	public function actionGrandgosier()
	{
		$this->comm = $this->getCommunes();
		$this->total = $this->getTotal("grand_gosier");
		$this->total_localite = $this->getTotalPerLocalite("grand_gosier");
		$this->total_f = $this->getTotalFeminin("grand_gosier");
		$this->total_m = $this->getTotalMasculin("grand_gosier");
		$this->total_enfantgarcon05 = $this->getTotalEnfantsGarcons05('grand_gosier');
		$this->total_enfantfille05 = $this->getTotalEnfantsFille05('grand_gosier');
		$this->total_enfantgarcon518 = $this->getTotalEnfants1518('grand_gosier');
		$this->total_enfantfille518 = $this->getTotalEnfants2518('grand_gosier');
	
		return $this->render('grandgosier',[
				'comm'=>$this->comm,
				'total'=>$this->total,
				'total_localite'=>$this->total_localite,
				'total_f'=>$this->total_f,
				'total_m'=>$this->total_m,
				'total_enfantgarcon05'=>$this->total_enfantgarcon05,
				'total_enfantfille05'=>$this->total_enfantfille05,
				'total_enfantgarcon518'=>$this->total_enfantgarcon518,
				'total_enfantfille518'=>$this->total_enfantfille518,
				]);
	}
	
	//thiotte
	public function actionThiotte()
	{
		$this->comm = $this->getCommunes();
		$this->total = $this->getTotal("thiotte");
		$this->total_localite = $this->getTotalPerLocalite("thiotte");
		$this->total_f = $this->getTotalFeminin("thiotte");
		$this->total_m = $this->getTotalMasculin("thiotte");
		$this->total_enfantgarcon05 = $this->getTotalEnfantsGarcons05('thiotte');
		$this->total_enfantfille05 = $this->getTotalEnfantsFille05('thiotte');
		$this->total_enfantgarcon518 = $this->getTotalEnfants1518('thiotte');
		$this->total_enfantfille518 = $this->getTotalEnfants2518('thiotte');
	
		return $this->render('thiotte',[
				'comm'=>$this->comm,
				'total'=>$this->total,
				'total_localite'=>$this->total_localite,

siis/views/rapport/ansespitre.php
<?php
use yii\helpers\Html;
use app\models\Famille;
use app\models\User;
use app\models\Operateurs;
use miloschuman\highcharts\Highcharts;
use yii\web\JsExpression;
/* @var $this yii\web\View */
$this->title = 'Rapport';

?>
<section class="content-header">
	<h1>
       Statistiques Anse-a-Pitre
       <small>Donnees d'Enquetes (Avril 2015)</small>
    </h1>
    <ol class="breadcrumb">
       <li><a href="#"><i class="fa fa-dashboard"></i> Accueil</a></li>
       <li class="active">Dashboard</li>
    </ol>
</section>

<section class="content">
	
	<div class="row">
		<div class="col-md-3 col-sm-6 col-xs-12">
              <div class="info-box bg-aqua">
                <span class="info-box-icon"><i class="fa fa-bookmark-o"></i></span>
                <div class="info-box-content">
                  <span class="info-box-text">Nombre de familles</span>
                  <span class="info-box-number">
                  	<?php
                       $number_famille = Famille::find()->where(['commune' => 'anse_pitres'])->count(); 
                       echo $number_famille; 
                    ?>
                  </span>
                  <div class="progress">
                    <div class="progress-bar" style="width: 100%"></div>
                  </div>
                  <span class="progress-description">
                    Enquete
                  </span>
                </div><!-- /.info-box-content -->
              </div><!-- /.info-box -->
            </div><!-- /.col -->
            
        <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="info-box bg-green">
                <span class="info-box-icon"><i class="fa fa-users"></i></span>
                <div class="info-box-content">
                  <span class="info-box-text">Nombre d'habitants</span>
                  <span class="info-box-number">
                  	<?= 
                       $total[0]; 
                    ?>
                  </span>
                  <div class="progress">
                    <div class="progress-bar" style="width: 100%"></div>
                  </div>
                  <span class="progress-description">
                    Enquete
                  </span>
                </div><!-- /.info-box-content -->
              </div><!-- /.info-box -->
            </div><!-- /.col -->
            
           <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="info-box bg-yellow">
                <span class="info-box-icon"><i class="fa fa-male"></i></span>
                <div class="info-box-content">
                  <span class="info-box-text">Total hommes</span>
                  <span class="info-box-number"><?= $total_m[0] ?></span>
                  <div class="progress">
                    <div class="progress-bar" style="width: <?php if($total[0] !=0) echo round(100*$total_m[0]/$total[0],2).'%' ?>"></div>
                  </div>
                  <span class="progress-description">
                    <?php if($total[0] !=0) echo round(100*$total_m[0]/$total[0],2).'%' ?>
                  </span>
                </div><!-- /.info-box-content -->
              </div><!-- /.info-box -->
            </div><!-- /.col -->
            
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="info-box bg-red">
                <span class="info-box-icon"><i class="fa fa-female"></i></span>
                <div class="info-box-content">
                  <span class="info-box-text">Total Femmes</span>
                  <span class="info-box-number"><?= $total_f[0] ?></span>
                  <div class="progress">
                    <div class="progress-bar" style="width: <?php if($total[0] !=0) echo round(100*$total_f[0]/$total[0],2).'%' ?>"></div>
                  </div>
                  <span class="progress-description">
                    <?php if($total[0] !=0) echo round(100*$total_f[0]/$total[0],2).'%' ?>
                  </span>
                </div><!-- /.info-box-content -->
              </div><!-- /.info-box -->
            </div><!-- /.col -->
          </div>
	
	
	<div class="row">
		<div class="col-xs-12">
           <div class="box box-solid">
               <div class="box-body">
                    <div class="row">
                    	<div class="col-md-3 col-sm-4">
                    		
                           <div style="margin-top: 15px;">
                               <ul class="nav nav-pills nav-stacked">
                                                	<?php 
                                                	
                                                	echo  '<li class="header">Actions</li>';
                                                	echo  '<li class="active">'. Html::a('<i class="fa fa-map-marker"></i> Demographie', ['']); '.</li>';
                                                	echo  '<li>'. Html::a('<i class="fa fa-eye-slash"></i> Cond. Sanitaires', ['/rapport/sanitaireansespitre']); '.</li>';
                                                	
                                                	echo  '<li>'. Html::a('<i class="fa fa-tasks"></i> Dimensions', ['/rapport/dimensions']); '.</li>';
                                                	
                                                	?>
                               </ul>
                           </div>
                    	</div>
                    	<div class="col-md-9 col-sm-8">
                    		<div class="row">
                    			<div class="col-md-8">
                    				<div class="box box-success">
		                                <div class="box-header">
		                                    <i class="fa fa-bar-chart-o"></i>
		                                    <h3 class="box-title">Rapport Demographique</h3>
		                                </div>
		                                <div class="box-body">
		                                		<?php 
				                                	echo Highcharts::widget([
				                                	    'options' => [
															'exporting' =>['enabled' => true],
				                                			'title' => ['text' => 'Donnees Demographiques'],
															'xAxis' => [
																'categories' => ['Anse-a-Pitres']
															],
				                                			'yAxis' => [
				                                				'title' => ['text' => 'Nombre Habitants']
				                                			],
				                                			'series' => [
				                                				['name' => 'Total', 
																 'type' => 'column',
																 'data' => $total,
																 'color' => new JsExpression('Highcharts.getOptions().colors[0]'),],
				                                				['name' => 'Feminin', 
																 'type' => 'column',
																 'data' =>  $total_f,
																 'color' => new JsExpression('Highcharts.getOptions().colors[1]'),],
																['name' => 'Masculin',
																 'type' => 'column',
																 'data' => $total_m,
																 'color' => new JsExpression('Highcharts.getOptions().colors[2]'),],
				                                			]
				                                		]
				                                	]);
			                                	
			                                	?>
		                                </div><!-- /.box-body -->
		                            </div><!-- /.box -->
                    			</div>
                    			<div class="col-md-4">
                    				<div class="box box-warning">
						                <div class="box-header with-border">
						                  <h3 class="box-title">Section Communale</h3>
						                </div><!-- /.box-header -->
						                <div class="box-footer no-padding">
						                  <ul class="nav nav-pills nav-stacked">
						                    <?php $arrlength = sizeof($total_localite); ?>
						                    <?php for ($i=0;$i<$arrlength;$i++):?>
						                    	
							    			 <li><a href="#"><?= $total_localite[$i][1] ?> <span class="pull-right text-red"><i class="fa fa-angle-down"></i> <?= $total_localite[$i][0] ?></span></a></li>
						                    
						                    <?php endfor; ?>
						                    
						                    </ul>
						                </div><!-- /.footer -->
						              </div>
						              
						              <div class="box box-warning">
						                <div class="box-header with-border">
						                  <h3 class="box-title">% Enfants / Population</h3>
						                </div><!-- /.box-header -->
						                <div class="box-footer no-padding">
						                  <ul class="nav nav-pills nav-stacked">
						                    <?php $arrlength = sizeof($total_enfantgarcon05); ?>
						                    <?php for ($i=0;$i<$arrlength;$i++):?>
							    			 <li><a href="#">Garcons (0 - 5) ans 
							    			    <span class="pull-right text-green"><i class="fa fa-angle-up"></i> <?= $total_enfantgarcon05[0] ?> - <?php  echo round(100*$total_enfantgarcon05[0]/$total[0],2).'%' ?></span></a>
							    			 </li>
						                    <?php endfor; ?>
						                    
						                    <?php $arrlength = sizeof($total_enfantfille05); ?>
						                    <?php for ($i=0;$i<$arrlength;$i++):?>
							    			 <li><a href="#">Filles (0 - 5) ans 
							    			    <span class="pull-right text-green"><i class="fa fa-angle-up"></i> <?= $total_enfantfille05[0] ?> - <?php  echo round(100*$total_enfantfille05[0]/$total[0],2).'%' ?></span></a>
							    			 </li>
						                    <?php endfor; ?>
						                    
						                    <?php $arrlength = sizeof($total_enfantgarcon518); ?>
						                    <?php for ($i=0;$i<$arrlength;$i++):?>
							    			 <li><a href="#">Garcons (5 - 18) ans 
							    			    <span class="pull-right text-green"><i class="fa fa-angle-up"></i> <?= $total_enfantgarcon518[0] ?> - <?php  echo round(100*$total_enfantgarcon518[0]/$total[0],2).'%' ?></span></a>
							    			 </li>
						                    <?php endfor; ?>
						                    
						                    <?php $arrlength = sizeof($total_enfantfille518); ?>
						                    <?php for ($i=0;$i<$arrlength;$i++):?>
							    			 <li><a href="#">Filles (5 - 18) ans 
							    			    <span class="pull-right text-green"><i class="fa fa-angle-up"></i> <?= $total_enfantfille518[0] ?> - <?php  echo round(100*$total_enfantfille518[0]/$total[0],2).'%' ?></span></a>
							    			 </li>
						                    <?php endfor; ?>
						                    </ul>
						                </div><!-- /.footer -->
						              </div>
                    			</div>
                    		</div>
                    	</div></div></div>
           </div>
        </div>
    </div>
	
</section>

siis/views/rapport/dimensions.php
<?php
use yii\helpers\Html;
use app\models\Famille;
use app\models\User;
use app\models\Operateurs;
use miloschuman\highcharts\Highcharts;
use yii\web\JsExpression;
use kartik\select2\Select2;

$this->title = 'Dimensions';

?>

<section class="content-header">
	<h1>
       Statistiques/Dimensions
       <small>Donnees d'Enquetes (Avril 2015)</small>
    </h1>
    <ol class="breadcrumb">
       <li><a href="#"><i class="fa fa-dashboard"></i> Accueil</a></li>
       <li class="active">Dimensions</li>
    </ol>
</section>

<section class="content">
	<div class="row">
		<div class="col-xs-12">
           <div class="box box-solid">
               <div class="box-body">
                    <div class="row">
                    	<div class="col-md-3 col-sm-4">
                           <div style="margin-top: 15px;">
                               <ul class="nav nav-pills nav-stacked">
                                   <?php 
                                        echo  '<li class="header">Actions</li>';
                                        echo  '<li>'. Html::a('<i class="fa fa-map-marker"></i> Demographie', ['/rapport/index']); '.</li>';
                                        echo  '<li>'. Html::a('<i class="fa fa-eye-slash"></i> Cond. Sanitaires', ['/rapport/sanitairethomassique']); '.</li>';
                                        echo  '<li class="active">'. Html::a('<i class="fa fa-tasks"></i> Dimensions', ['/rapport/dimensions']); '.</li>';
                                   ?>
                               </ul>
                           </div>
                    	</div>
                    	<div class="col-md-9 col-sm-8">
                    		<div class="row">
                    			<h4 class="page-header">Dimensions/Donnees</h4>
                    			<div class="col-md-9">
                    				<?php echo $this->render('/options/_form', ['model' => $model]); ?>
                    			</div>
                    		</div>
                    	</div>
                    </div>
                </div>
            </div>
         </div>
     </div>
</section>

siis/views/rapport/pdfstats.php
<?php

use yii\helpers\Html;

use app\models\Options;
?>

<div class="content">
	<div class="container">
		<br/>
		<div class="row">
			<div class="Container">
		    	<h4 class="content-title" style="text-align:center;">
					<span> KORE FANMI - DONNEES ENQUETES </span>
				</h4>
				<h5 class="content-title" style="text-align:center;">
					<span> <?php 
								if(isset($section_communale) || isset($localite)){
									echo strtoupper($commune);
								}else{
									echo strtoupper($commune).' / '.strtoupper($section_communale).' / '.strtoupper($localite);
								}
						   ?> </span>
				</h5>
		    </div>
		</div>
		<br/>
		<div class="row">
			<div class="container">
				<?php foreach($data as $record): ?>
					<?php 
						$result = array();
						$xy = new Options();
						$result = $xy->getData($record, $commune, $section_communale, $localite);
						$ar = json_decode($record->options);
					?>
					
					<table width="100%" border="0">
						<tr>
						   <td align="left"><?php echo ' '.$record->question; ?></td>
						</tr>
						<tr>
						   <td align="center"></td>
						</tr>
					</table> 
					
					<table width="100%" border="0">  
					    <tr>
					      	<td width="100%">
					      		<table width="100%" border="1" cellpadding="0" cellspacing="0" bordercolor="#666666">
					      			<tr>
							          <td width="10%" align="center" bgcolor="#E5E5E5">Commune</td>
							          <td width="10%" align="center" bgcolor="#E5E5E5">Section Communale</td>
							          <td width="10%" align="center" bgcolor="#E5E5E5">Localite</td>
							          <td width="60%" align="center" bgcolor="#E5E5E5">Reponse</td>
							          <td width="10%" align="center" bgcolor="#E5E5E5">Quantite</td>
							        </tr>	
							        <?php $o = 0;?>
					      			<?php foreach($result as $record2): ?>
					      				<tr>
					      					<td>&nbsp;<?= iconv("iso-8859-1","UTF-8",$commune) ?></td>
						      				<td>&nbsp;<?= iconv("iso-8859-1","UTF-8",$section_communale) ?></td>
						      				<td>&nbsp;<?= iconv("iso-8859-1","UTF-8",$localite) ?></td>
						      				<td>&nbsp;<?php
						      					if($result[$o][1] == 0){
						      						echo "-- PA REPONN --";
						      					}else{
						      						echo $ar[$result[$o][1]-1];
						      					}
						      				?></td>
						      				<td>&nbsp;<?= iconv("iso-8859-1","UTF-8",$result[$o][0]) ?></td>
					      				</tr>
					      				<?php $o += 1;?>
					      			<?php endforeach;?>
					      			<tr>
							          <td>&nbsp;</td>
							          <td>&nbsp;</td>
							          <td>&nbsp;</td>
							          <td>&nbsp;</td>
							          <td>&nbsp;</td>
							        </tr>
					      		</table>
					      	</td>
					      </tr>
					 </table>
					 <br/><br/>
				<?php endforeach;?>
			</div>
		</div>
	</div>
</div>