siis/controllers/PlansController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Plans;
use app\models\ScrPlans;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use kartik\mpdf\Pdf;
use yii\helpers\Url;
use app\models\User;
use app\models\Operateurs;
use Yii\db;
use yii\data\ActiveDataProvider;
use app\models\Activites;
/**
 * PlansController implements the CRUD actions for Plans model.
 */
class PlansController extends Controller
{
	public $layout = 'main_dashboard2';
	public $data = array();
	
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    public function actionIndex2()
    {
    	$this->dataBindingPage();
    	$searchModel = new ScrPlans();
    	$model = new Plans();
    	$model->scenario = 'plants';
    	$user = User::findOne(Yii::$app->user->identity->id);
    	$operateur = Operateurs::findOne($user->idOperateurs);
    	
    	$dataProvider = $searchModel->search17(Yii::$app->request->queryParams, $operateur->id);
    	
    	$dataProvider->pagination->pageSize=8;
    	
    	if ($model->load(Yii::$app->request->post())) {
    		//print_r($model->akf);
    		$time = new \DateTime('now', new \DateTimeZone('UTC'));
    		//$model->annee = $time->format('Y');
    		$model->ts = $operateur->id;
    		$model->commune = $operateur->commune_lie;
    		$model->is_sync = 1;
    		$model->mode = 2;
    		$model->isPlanned = 1;
    		$model->isPlannedBy = $operateur->id;
    		$model->isPlannedOn = date('Y-m-d');
        	$model->isMonitoring = 1;
        	$model->isDeleted = 0;
        	$model->isClosed = 0;
    		 
    		if($model->save(false)){
    			//print_r('ok');
    			return $this->redirect(['/activites/create2', 'id' => $model->id]);
    		}
    		//return $this->redirect(['create', 'id' => $operateur->id]);
    	} else {
    		return $this->render('index2', [
    				'searchModel' => $searchModel,
    				'dataProvider' => $dataProvider,
    				'activites' => $this->data[0],
    				'plan' => $this->data[1],
    				'akf' => $this->data[2],
    				'model' => $model
    		]);
    	}
    }
    /**
     * Lists all Plans models.
     * @return mixed
     */
    public function actionIndex()
    {
    	$this->dataBindingPage();
        $searchModel = new ScrPlans();
        $model = new Plans();
        
        $user = User::findOne(Yii::$app->user->identity->id);
        $operateur = Operateurs::findOne($user->idOperateurs);
        
        $dataProvider = $searchModel->search12(Yii::$app->request->queryParams, $operateur->id);
        
        $dataProvider->pagination->pageSize=8;
        
        if ($model->load(Yii::$app->request->post())) {
        	//print_r($model->dimagi);
        	$time = new \DateTime('now', new \DateTimeZone('UTC'));
        	//$model->annee = $time->format('Y');
        	$model->ts = $operateur->id;
        	$model->commune = $operateur->commune_lie;
        	$model->is_sync = 1;
        	$model->mode = 1;
        	$model->isPlanned = 1;
        	$model->isPlannedBy = $operateur->id;
        	$model->isPlannedOn = date('Y-m-d');
        	$model->isMonitoring = 1;
        	$model->isDeleted = 0;
        	$model->isClosed = 0;
        	
        	if($model->save()){
        		return $this->redirect(['/activites/create', 'id' => $model->id]);
        	}
        	//return $this->redirect(['create', 'id' => $operateur->id]);
        } else {
        	return $this->render('index', [
        			'searchModel' => $searchModel,
        			'dataProvider' => $dataProvider,
        			'activites' => $this->data[0],
        			'plan' => $this->data[1],
        			'akf' => $this->data[2],
        			'model' => $model
        	]);
        }
        /*if(Yii::$app->request->queryParams){ print_r('wi');}
        else{ print_r('wi 4');}*/
        
        /*$dataProvider = new ActiveDataProvider([
        	'query' => Plans::find()->where(['ts' => $operateur->id]),
        	'pagination' => [
        		'pageSize' => 10,
        	],
        ]);*/
    }

    public function actionSuivipdf($id) {
    	$plan = Plans::findOne($id);
    	 
    	$data = new ActiveDataProvider([
    		'query' =>Activites::find()->where(['id_plan' => $id]),
    	]);
    	 
    	$content = $this->renderPartial('suivipdf', ['activites' => $data, 'plan' => $plan]);
    	
    	$pdf = new Pdf();
    	 
    	if($plan->mode == 1){
    		$operateur = Operateurs::findOne($plan->akf);
    		$pdf->filename = 'CF'.'-'.$operateur->nom.'-'.$operateur->prenom.'/'.date('Y-m-d');
    	}
    	else{
    		$operateur = Operateurs::findOne($plan->ts);
    		$pdf->filename = 'CF'.'-'.$operateur->nom.'-'.$operateur->prenom.'/'.date('Y-m-d');
    	}
    	 
    	$pdf->content = Pdf::MODE_CORE;
    	$pdf->mode = Pdf::MODE_BLANK;
    	$pdf->cssFile = '@vendor/kartik-v/yii2-mpdf/assets/kv-mpdf-bootstrap.min.css';
    	$pdf->defaultFontSize = 10;
    	$pdf->defaultFont = 'helvetica';
    	$pdf->format = array(216,285);
    	$pdf->orientation = Pdf::ORIENT_LANDSCAPE;
    	$pdf->destination = Pdf::DEST_BROWSER;
    	 
    	$pdf->content = $content;
    	$pdf->options = ['title' => 'SIIS Report Suivi'];
    	$pdf->methods = [
	    	'SetHeader'=>['SIIS Report Suivi'],
	    	'SetFooter'=>['{PAGENO}'],
    	];
    	
    	$pdf->options = [
	    	'title' => 'Fiche de Suivi',
	    	'autoScriptToLang' => true,
	    	'ignore_invalid_utf8' => true,
	    	'tabSpaces' => 4
    	];
    	
    	// return the pdf output as per the destination setting
    	return $pdf->render();
    }
    
    // Privacy statement output demo
    public function actionPdf($id) {
    	
    	$plan = Plans::findOne($id);
    	
    	$data = new ActiveDataProvider([
    		'query' =>Activites::find()->where(['id_plan' => $id]),
    	]);
    	
    	$content = $this->renderPartial('pdf', ['activites' => $data, 'plan' => $plan]);
    	 
    	$pdf = new Pdf();
    	
    	if($plan->mode == 1){
    		$operateur = Operateurs::findOne($plan->akf);
    		$pdf->filename = 'CF'.'-'.$operateur->nom.'-'.$operateur->prenom.'/'.date('Y-m-d');
    	}
    	else{
    		$operateur = Operateurs::findOne($plan->ts);
    		$pdf->filename = 'CF'.'-'.$operateur->nom.'-'.$operateur->prenom.'/'.date('Y-m-d');
    	}
    	
    	$pdf->content = Pdf::MODE_CORE;
    	$pdf->mode = Pdf::MODE_BLANK;
    	$pdf->cssFile = '@vendor/kartik-v/yii2-mpdf/assets/kv-mpdf-bootstrap.min.css';
    	//$pdf->cssInline = '.kv-heading-1{font-size:4px}';
    	$pdf->defaultFontSize = 10;
    	$pdf->defaultFont = 'helvetica';
    	$pdf->format = array(216,285);
    	$pdf->orientation = Pdf::ORIENT_LANDSCAPE;
    	$pdf->destination = Pdf::DEST_BROWSER;
    	
    	$pdf->content = $content;
    	$pdf->options = ['title' => 'SIIS Report Planning'];
    	$pdf->methods = [
    	'SetHeader'=>['SIIS Report Header'],
    	'SetFooter'=>['{PAGENO}'],
    	];
    	$pdf->options = [
    		'title' => 'Plan de Travail',
    		'autoScriptToLang' => true,
    		'ignore_invalid_utf8' => true,
    		'tabSpaces' => 4
    	];
    	 
    	// return the pdf output as per the destination setting
    	return $pdf->render();
    }
    
    /**
     * Displays a single Plans model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
    	$plan = Plans::findOne($id);
    	$op_akf = Operateurs::findOne($plan->akf);
    	
    	$data = new ActiveDataProvider([
    		'query' => Activites::find()->where(['id_plan' => $plan->id]),
    	]);
    	
    	$data->pagination->pageSize=8;
    	
        return $this->render('view', [
            'model' => $this->findModel($id),
        	'model1' => $op_akf,
        	'dataProvider' => $data
        ]);
    }

    /**
     * Creates a new Plans model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($id)
    {
        $model = new Plans();
        $operateur1 = Operateurs::findOne($id);
        $this->dataBindingPage();
        
        $user = User::findOne(Yii::$app->user->identity->id);
        $operateur = Operateurs::findOne($user->idOperateurs);
        
        $time = new \DateTime('now', new \DateTimeZone('UTC'));
        //$model->annee = $time->format('Y');
        $model->ts = $operateur->id;
        $model->akf = $id;
        $model->commune = $operateur->commune_lie;
        $model->mode = 1;
        $model->is_sync = 1;
        $model->isPlanned = 1;
        $model->isPlannedBy = $operateur->id;
        $model->isPlannedOn = date('Y-m-d');
        $model->isMonitoring = 1;
        $model->isDeleted = 0;
        $model->isClosed = 0;
        
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
        	Yii::$app->session->setFlash('kv-detail-success', 'Saved record successfully');
        	Yii::$app->session->setFlash('kv-detail-warning', 'A last warning for completing all data.');
        	Yii::$app->session->setFlash('kv-detail-info', '<b>Note:</b> You can proceed by clicking <a href="#">this link</a>.');
        	
            return $this->redirect(['/activites/create', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            	'model1' => $operateur1,
            	'plan' => $this->data[1],
            	'akf' => $this->data[2],
            	'dataProvider' => $this->data[0]
            ]);
        }
        
        /*$view = 'create';
        $record = new Plans();
        
        if ($record->load($_POST) && $record->save()) {
        	$record->refresh(); // just in case of some DB logic
        	$view = 'view';
        }
        
        return $this->renderAjax($view, [
        		'model' => $record,
        		]);*/
    }

    /**
     * Updates an existing Plans model.
     * If update is successful, the browser will be redirected to the 'view' page.

siis/views/plans/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Plans */
/* @var $form yii\widgets\ActiveForm */
?>

    <?php $form = ActiveForm::begin([
    		]); ?>
	    <div class="box-body">
	    	<div id="msg" class="row" style="display : none;">
				<div class="col-md-12">
					<div class="alert alert-danger alert-dismissable">
						 <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
						 Duplicate Planning not allowed. Choose a another month.
					</div>
				</div>
			</div>
		    <div class="row">
				<div class="col-md-6">
					<?= $form->field($model, 'mois')->dropDownList(
				          ['Janvier'=>'Janvier','Fevrier'=>'Fevrier', 'Mars'=>'Mars','Avril'=>'Avril',
		                   'Mai'=>'Mai','Juin'=>'Juin', 'Juillet'=>'Juillet','Aout'=>'Aout',
		                   'Septembre'=>'Septembre', 'Octobre'=>'Octobre', 'Novembre'=>'Novembre',
		                   'Decembre'=>'Decembre'], ['prompt'=>'--Choisir un mois --', 'onchange' => 'showUser2(this.value)']
				    );?>
				</div>
				<div class="col-md-6">
					 <?= $form->field($model,'annee')
		          		->dropDownList(
				          ['2012'=>'2012','2013'=>'2013', '2014'=>'2014','2015'=>'2015',
		                   '2016'=>'2016'], ['prompt'=>'--Choisir une annee --','disabled' => true,'onchange' => 'showUser(this.value)']
				    )?>
				</div>
			</div>	
			<div class="row">
				<div class="col-md-6">
					 <?= $form->field($model, 'dimagi')->checkbox(array('label'=>''))
							->label('Will upload to Dimagi'); ?> 
				</div>
			</div>	
	    </div>
	    <div class="box-footer">
	        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary', 'id' => 'ok']) ?>
	    </div>
    <?php ActiveForm::end(); ?>

siis/views/plans/_search2.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
/* @var $this yii\web\View */
/* @var $model app\models\ScrPlans */
/* @var $form yii\widgets\ActiveForm */
?>



<?php $form = ActiveForm::begin([
	    'action' => ['index2'],
	    'method' => 'get',
		'options' => ['class' => 'form-inline'],
	]); ?>
	    <div class="input-group">
	      
	       <?= $form->field($model, 'mois')->dropDownList(
			  ['Janvier'=>'Janvier','Fevrier'=>'Fevrier', 'Mars'=>'Mars','Avril'=>'Avril',
                   'Mai'=>'Mai','Juin'=>'Juin', 'Juillet'=>'Juillet','Aout'=>'Aout',
                   'Septembre'=>'Septembre', 'Octobre'=>'Octobre', 'Novembre'=>'Novembre',
                   'Decembre'=>'Decembre'], ['prompt' => 'Choisir un mois', 'class'=>'form-control input-sm'])->label(false)
			  
	      ?>
	      <span class="input-group-btn" style="width:0px;"></span>
		  <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-sm btn-primary']) ?>
		</div>
<?php ActiveForm::end(); ?>

siis/views/plans/calendar.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use yii\data\ActiveDataProvider;
use app\models\User;
use app\models\Operateurs;
use app\models\Plans;

/* @var $this yii\web\View */
/* @var $searchModel app\models\ScrPlans */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = "Plans";
$x =Yii::$app->getRequest()->getQueryParam('id');
$titre = '';
$plan = Plans::findOne($x);
$a = new Plans();
$date = "'$plan->annee-".$a->getMonthNumber($plan->mois)."-01'";

$script = <<< JS
$(function () {

        /* initialize the calendar
         -----------------------------------------------------------------*/
        //Date for the calendar events (dummy data)
        var date = new Date();
        m = 'December',
        y = date.getFullYear();


		$('#calendar').fullCalendar({
          header: {
            left: 'prev,next today',
            center: 'title',
            right: 'month,agendaWeek,agendaDay'
          },

          buttonText: {
            today: 'Aujourd\'hui',
            month: 'mois',
            week: 'semaine',
            day: 'jour'
          },

          events: '?r=activites/calendar1&id=$x',

		  dayClick: function(date, jsEvent, view) {
				alert('Clicked on: ' + date.format());
		 	},

          viewRender: function(view, element) {
		    $('#calendar').fullCalendar( 'gotoDate', $date );
		  },
		    		
          editable: false,
          droppable: false, // this allows things to be dropped onto the calendar !!!

		  eventDrop: function(event, delta, revertFunc) {
			if (!confirm("Are you sure about this change?")){
				revertFunc();
			}
		  },
		
		  eventClick:  function(event, jsEvent, view) {
            //$('#modalTitle').html(event.title);
           // $('#modalBody').html(event.description);
            //$('#eventUrl').attr('href',event.url);
            //$('#fullCalModal').modal('show');
          },

		  eventDragStop: function( event, jsEvent, ui, view ) {
             // alert(event.title + " was dropped on " + event.start.format());
		  },

		  eventReceive: function( event ) {
			
		  },

          drop: function (date, allDay) { // this function is called when something is dropped

            // retrieve the dropped element's stored Event Object
            var originalEventObject = $(this).data('eventObject');

            // we need to copy it, so that multiple events don't have a reference to the same object
            var copiedEventObject = $.extend({}, originalEventObject);

            // assign it the date that was reported
            copiedEventObject.start = date;
            copiedEventObject.allDay = allDay;
            copiedEventObject.backgroundColor = $(this).css("background-color");
            copiedEventObject.borderColor = $(this).css("border-color");

            // render the event on the calendar
            // the last `true` argument determines if the event "sticks" (http://arshaw.com/fullcalendar/docs/event_rendering/renderEvent/)
            $('#calendar').fullCalendar('renderEvent', copiedEventObject, true);

            // is the "remove after drop" checkbox checked?
            if ($('#drop-remove').is(':checked')) {
              // if so, remove the element from the "Draggable Events" list
              $(this).remove();
            }

          }

        });

		function custom_sort(a, b) {
		    return new Date(a.start).getTime() - new Date(b.start).getTime();
		}

		events_array.sort(custom_sort);

    	$('#calendar').fullCalendar('gotoDate', "2016-11-10");
      });
JS;
$this->registerJs($script, \yii\web\View::POS_END);

?>

<section class="content-header">
	<h1>
       Dashboard
       <small>Centre de Gestion</small>
    </h1>
    <ol class="breadcrumb">
       <li><a href="#"><i class="fa fa-dashboard"></i> Accueil</a></li>
       <li class="active">Dashboard</li>
    </ol>
</section>

<section class="content">
	<div class="row">
		<div class="col-xs-12">
			<div class="box box-solid">
				<div class="box-body">
					<div class="row">
						<div class="col-md-3 col-sm-4">
							<div class="box-header">
                                                <i class="fa fa-inbox"></i>
                                                <h3 class="box-title">PANEL DE GESTION</h3>
                                            </div>
                                 <!-- compose message btn -->
                                 <a class="btn btn-block btn-primary">
                                      <i class="fa fa-plus-square"></i> Creer un plan de travail</a>
                                 <!-- Navigation - folders-->
                                 <div style="margin-top: 15px;">
                                      <ul class="nav nav-pills nav-stacked">
                                                	<?php 
                                                	
                                                	$user = User::findOne(Yii::$app->user->identity->id);
                                                	$operateur = Operateurs::findOne($user->idOperateurs);
                                                	echo  '<li class="header">Actions</li>';
                                                	if($plan->mode == 1){
                                                		echo  '<li class="active">'. Html::a('<i class="fa fa-retweet"></i>Plans AKF', ['/plans/index', 'id' => $operateur->id]); '.</li>';
														echo  '<li>'. Html::a('<i class="fa fa-angle-up"></i>Activites AKF', ['/activites/index']); '.</li>';
														echo  '<li>'.Html::a('<i class="fa  fa-ellipsis-v"></i> Plans TS', ['/plans/index2']); '.</li>';

                                                	}elseif ($plan->mode == 2){
                                                		echo  '<li>'. Html::a('<i class="fa fa-retweet"></i>Plans AKF', ['/plans/index', 'id' => $operateur->id]); '.</li>';
														echo  '<li>'. Html::a('<i class="fa fa-angle-up"></i>Activites AKF', ['/activites/index']); '.</li>';
														echo  '<li class="active">'.Html::a('<i class="fa  fa-ellipsis-v"></i> Plans TS', ['/plans/index2']); '.</li>';
														
	                                                }
                                                	?>
                                                </ul>
                                            </div>
						</div>
						
						<div class="col-md-9 col-sm-8">
							<div class="box box-primary">
						                <div class="box-body no-padding">
						                  <!-- THE CALENDAR -->
						                  <div id="calendar"></div>
						                </div><!-- /.box-body -->
						              </div><!-- /. box -->
						</div>
					</div></div></div></div></div>
</section>

siis/views/plans/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use app\models\Activites;
use app\models\User;
use app\models\Operateurs;
use kartik\grid\GridView;
use yii\data\ActiveDataProvider;
use app\models\Plans;
use app\models\TypeThemes;
use app\models\TypeActivites;

/* @var $this yii\web\View */
/* @var $model app\models\Plans */

$this->title = 'Details Plan';
$x =Yii::$app->getRequest()->getQueryParam('id');
$plan = Plans::findOne($x);
?>

<section class="content-header">
	<h1>
       Plan
       <small>Details du Plan <strong>
       <?php 
            if($plan!=null && $plan->mode == 1){
				if($model1!=null && $model!=null)
            	echo ' de '.$model1->nom.' '.$model1->prenom.' ( '.$model->mois.' '.$model->annee.' )';
            }
       ?>
       </strong></small>
    </h1>
    <ol class="breadcrumb">
       <li><a href="#"><i class="fa fa-dashboard"></i> Accueil</a></li>
       <li class="active">Details Plan</li>
    </ol>
</section>

<section class="content">
    <div class="row">
	
	
	</div>
	<div class="row">
		<div class="col-xs-12">
           <div class="box box-solid">
               <div class="box-body">
                    <div class="row">
                    	<div class="col-md-3 col-sm-4">
                    		<div class="box-header">
                                                <i class="fa fa-inbox"></i>
                                                <h3 class="box-title">PANEL DE GESTION</h3>
                                            </div>
                                               
                                            <?php
                                               if($plan->mode == 1){
                                               		echo Html::a('<i class="fa fa-plus-square"></i> Ajouter Activites (AKF)',
                                                    ['/activites/create', 'id' => $model->id], ['class' => 'btn btn-block btn-primary']);
                                               }elseif ($plan->mode == 2){
                                               		echo Html::a('<i class="fa fa-plus-square"></i> Ajouter Activites (TS)',
		                                            ['/activites/create2', 'id' => $model->id], ['class' => 'btn btn-block btn-primary']);
                                               }
                                               
                                            	
                                            ?>
                                            <!-- Navigation - folders-->
                                            <div style="margin-top: 15px;">
                                                <ul class="nav nav-pills nav-stacked">
                                                    <?php 
                                                	
                                                	$user = User::findOne(Yii::$app->user->identity->id);
                                                	$operateur = Operateurs::findOne($user->idOperateurs);
                                                	echo  '<li class="header">Actions</li>';
                                                	if($plan->mode == 1){
                                                		echo  '<li class="active">'. Html::a('<i class="fa fa-retweet"></i>Plans AKF', ['/plans/index', 'id' => $operateur->id]); '.</li>';
														echo  '<li>'. Html::a('<i class="fa fa-angle-up"></i>Activites AKF', ['/activites/index']); '.</li>';
														echo  '<li>'.Html::a('<i class="fa  fa-ellipsis-v"></i> Plans TS', ['/plans/index2']); '.</li>';

                                                	}elseif ($plan->mode == 2){
                                                		echo  '<li>'. Html::a('<i class="fa fa-retweet"></i>Plans AKF', ['/plans/index', 'id' => $operateur->id]); '.</li>';
														echo  '<li>'. Html::a('<i class="fa fa-angle-up"></i>Activites AKF', ['/activites/index']); '.</li>';
														echo  '<li class="active">'.Html::a('<i class="fa  fa-ellipsis-v"></i> Plans TS', ['/plans/index2']); '.</li>';
														
	                                                }
                                                	?>
                                                </ul>
                                            </div>
                    	</div>
                    	
                    	<div class="col-md-9 col-sm-8">
                    	    <div class="row">
                    	       <div class="col-md-12">
                    	          <?php 
                    	          
                    	            $activites = Activites::find()
                    	            	->where(['id_plan' => $model->id])
                    	                ->count();
                    	            	
                    	          	if($activites == 0)
                                    {
                                    	echo '<div class="alert alert-warning">';
                                    		echo '<span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>';
                                    		echo '<span class="sr-only">Error:</span>';
                                    		echo 'ATTENTION, CE PLAN NE CONTIENT AUCUN ELEMENT';
                                    	echo '</div>';
                                    }
                    	          ?>
                    	    </div></div>
                    		<div class="row">
                    			<div  class="col-md-12">
                    				<h3 class="page-header">Liste des Activites associees</h3>
                    				
                    				<?php 
					                    			echo GridView::widget([
					                    				'dataProvider' => $dataProvider,
                                                        'export' => false,
														'showPageSummary' => false,
														'bordered' => false,
														'responsive' => true,
														'hover' => true,
														'rowOptions' => function($model1){
															//$count = Plans::find()->where(['akf' => $model1->id])->count();
															if($model1->isDone != 0 && $model1->isDone != null){
																return ['class' => 'success',];
															}
															elseif($model1->isDone == 0 || $model1->isDone == null){
																return ['class' => 'warning'];
															}
														},
                                                        'columns' => [
	                                                         ['class' => 'yii\grid\SerialColumn'],
                                                             
															[
																'header'=>'Type Activite',
																'format'=>'raw',
																'value'=> function ($model, $key, $index, $widget) {
	                                                                $type = TypeActivites::findOne($model->id_type_activite);
																	return $type->libelle;
																},
															], 'date_activite', 'lieu', 'description',
															[
															'header'=>'Etat',
															'format'=>'raw',
															'value'=> function ($model1, $key, $index, $widget) {
																if($model1->isDone != 0 && $model1->isDone != null){
																	return '<span class="label label-success">realise</span>';
																}
																elseif($model1->isDone == 0 || $model1->isDone == null){
																	return '<span class="label label-warning">non realise</span>';
																}
															},
															],
                                                             [
																'class' => 'yii\grid\ActionColumn',
																'template' => '{activites} {details} {effacer}',
																'buttons' => [
																'activites' => function ($url,$model) {
																	return Html::a(
																			'<span class="glyphicon glyphicon-edit"></span>',
																			['activites/view', 'id' => $model->id],
                                                                            ['class' => 'btn btn-xs btn-default']);
																},
																'details' => function ($url,$model) {
																	return Html::a(
																			'<span class="glyphicon glyphicon-folder-open"></span>',
																			['sous-activites/index', 'id' => $model->id],
																			['class' => 'btn btn-xs btn-warning']);
																},
																'effacer' => function ($url,$model) {
																	$x =Yii::$app->getRequest()->getQueryParam('id');
																	$count = Plans::find()->where(['id' => $model->id, 'isMonitoring' => 0,
																			'isExecuted' => 1, 'isDeleted' => 0, 'isClosed' => 0, 'mode' => 1])->count();
																	
																	$count1 = Plans::find()->where(['id' => $model->id, 'isMonitoring' => 0,
																			'isExecuted' => 1, 'isDeleted' => 0, 'isClosed' => 1, 'mode' => 1])->count();
																	
																	if($count == 0 && $count1 == 0){
																		return "";
																	}
																	else{ 
																		return Html::a(
																				'<span class="fa fa-trash-o"></span>',
																				['activites/delete', 'id' => $model->id, 'id1' => $x],
																				['class' => 'btn btn-xs btn-danger', 'data-method' => 'post',
																						'data-confirm'=>'Voulez vous vraiment effacer cette activite?',
																						'onmouseover'=>'Tip("Effacer AKF")', 'onmouseout'=>'UnTip()']);
																	}
																	
																	
																},
																],
                                                         ]]
					                    			 ]);
					                    		?> 
                    			</div>
                    			
                    			
                    		</div>
                    	</div>
                    </div>
               </div>
           </div>
        </div>
	</div>
</section>